config system interface
    edit port2
        set mode static
        set ip 203.0.113.2 255.255.255.252
        set allowaccess ping https ssh
    next
    edit port3
        set mode static
        set ip 192.0.2.1 255.255.255.0
        set allowaccess ping https ssh
        set role dmz
    next
    edit port4
        set mode static
        set ip 198.51.100.1 255.255.255.0
        set allowaccess ping https ssh
        set role lan
    next
end

config router static
    edit 1
        set gateway 203.0.113.1
        set device port2
    next
    edit 2
        set dst 10.10.10.0 255.255.255.0
        set gateway 203.0.113.1
        set device port2
    next
end

config firewall policy
    edit 1
        set name client-to-dmz
        set srcintf port2
        set dstintf port3
        set srcaddr all
        set dstaddr all
        set action accept
        set schedule always
        set service ALL
    next
    edit 2
        set name client-to-work
        set srcintf port2
        set dstintf port4
        set srcaddr all
        set dstaddr all
        set action accept
        set schedule always
        set service ALL
    next
    edit 3
        set name dmz-to-real-wan
        set srcintf port3
        set dstintf port2
        set srcaddr all
        set dstaddr all
        set action accept
        set schedule always
        set service ALL
        set nat enable
    next
    edit 4
        set name work-to-real-wan
        set srcintf port4
        set dstintf port2
        set srcaddr all
        set dstaddr all
        set action accept
        set schedule always
        set service ALL
        set nat enable
    next
end
