[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "engulf-clab"
version = "0.1.1"
description = "Engulf wrapper for Containerlab"
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
dependencies = [
    "engulf>=0.1,<1",
    "engulf-executable-wrapper>=0.1,<1",
]

[project.scripts]
eclab = "engulf_clab.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/engulf_clab"]

[tool.ruff]
target-version = "py314"

[tool.mypy]
python_version = "3.14"
strict = true
files = ["src/engulf_clab"]
