"""Public API for contributor-owned license-pool metadata."""

from .contract import (
    NO_DEFAULT,
    POOL_METADATA_CONTRIBUTOR_GROUP,
    POOL_METADATA_FILENAME,
    POOL_METADATA_VERSION,
    LicensePoolMetadataContext,
    LicensePoolMetadataContributor,
    LicensePoolMetadataError,
    LicensePoolMetadataVariableResolver,
    LicensePoolVariable,
    LicensePoolVariableType,
    PoolMetadata,
    discover_metadata_contributors,
    format_license_pool_variable_value,
    load_pool_metadata,
    metadata_variables_for,
    parse_license_pool_variable_value,
    validate_contribution,
    validate_license_pool_variable_value,
)

__all__ = [
    "NO_DEFAULT",
    "POOL_METADATA_CONTRIBUTOR_GROUP",
    "POOL_METADATA_FILENAME",
    "POOL_METADATA_VERSION",
    "LicensePoolMetadataContext",
    "LicensePoolMetadataContributor",
    "LicensePoolMetadataError",
    "LicensePoolMetadataVariableResolver",
    "LicensePoolVariable",
    "LicensePoolVariableType",
    "PoolMetadata",
    "discover_metadata_contributors",
    "format_license_pool_variable_value",
    "load_pool_metadata",
    "metadata_variables_for",
    "parse_license_pool_variable_value",
    "validate_contribution",
    "validate_license_pool_variable_value",
]
